# Generated by Django 6.0.1 on 2026-01-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('I.T.', 'I.T.'), ('Finance', 'Finance'), ('HR', 'HR'), ('Admission', 'Admission')], default='I.T.', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
    ]
