# Generated by Django 6.0.1 on 2026-01-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reply_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
