# Generated by Django 6.0.1 on 2026-01-24 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_phone_ticket_staff_id_ticket_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='e.g. UGC-STF-1004', max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Master Staff List',
                'verbose_name_plural': 'Master Staff List',
            },
        ),
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(help_text='e.g. UGC-STU-2026-001', max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Master Student List',
                'verbose_name_plural': 'Master Student List',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='validated_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.staffmaster'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='validated_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.studentmaster'),
        ),
    ]
