# Generated by Django 6.0.1 on 2026-01-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_staffmaster_studentmaster_ticket_validated_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaster',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
