# Generated by Django 6.0.1 on 2026-01-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_studentmaster_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmaster',
            old_name='official_email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('VISITOR', 'Visitor')], default='VISITOR', max_length=10),
        ),
    ]
