# Generated by Django 6.0.1 on 2026-01-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_rename_official_email_staffmaster_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('I.T.', 'I.T.'), ('Finance', 'Finance'), ('HR', 'HR'), ('Admission', 'Admission'), ('Student Support Service', 'Student Support Service')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('I.T.', 'I.T.'), ('Finance', 'Finance'), ('HR', 'HR'), ('Admission', 'Admission'), ('Student Support Service', 'Student Support Service')], default='I.T.', max_length=50),
        ),
    ]
