# Generated by Django 6.0.1 on 2026-01-27 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_staffprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('I.T.', 'I.T.'), ('Finance', 'Finance'), ('HR', 'HR'), ('Admission', 'Admission'), ('Student Support Service', 'Student Support Service'), ('Super Command', 'Super Command')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(help_text='e.g. Head Admin, HR Manager', max_length=50),
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
