# Generated by Django 6.0.1 on 2026-01-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_staffprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_reply_by',
            field=models.CharField(blank=True, choices=[('STAFF', 'Staff'), ('USER', 'User')], max_length=20, null=True),
        ),
    ]
