# Generated by Django 6.0.1 on 2026-01-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_last_reply_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='tickets.ticketmessage'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
